plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "com.google.devtools.ksp"
    id "dagger.hilt.android.plugin"
}

android {
    namespace = "com.beacon.shared"
    compileSdk 34

    defaultConfig {
        minSdk 26
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.2"

    implementation platform("com.google.firebase:firebase-bom:33.8.0")
    implementation "com.google.firebase:firebase-firestore"
    implementation "com.google.firebase:firebase-database"
    
    // Hilt
    implementation "com.google.dagger:hilt-android:2.51.1"
    ksp "com.google.dagger:hilt-compiler:2.51.1"
}
